"""creating a column to hold description on the table holding teams

Revision ID: 9b53415ace9e
Revises: f4d17b82bfed
Create Date: 2018-09-19 12:40:11.878453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b53415ace9e'
down_revision = 'f4d17b82bfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'description')
    # ### end Alembic commands ###
