"""creating a columns on the team and coach tables 

Revision ID: da46ddc76e19
Revises: 9b53415ace9e
Create Date: 2018-09-19 14:09:53.706694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da46ddc76e19'
down_revision = '9b53415ace9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('description', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_column('profiles', 'email')
    op.drop_column('coaches', 'description')
    # ### end Alembic commands ###
