"""creating a column for location

Revision ID: dc9dfee27dfa
Revises: da46ddc76e19
Create Date: 2018-09-19 14:55:00.319100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9dfee27dfa'
down_revision = 'da46ddc76e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'location')
    # ### end Alembic commands ###
