"""creating a column to hold email

Revision ID: f8f5f4b3b169
Revises: a6ea9f14acd7
Create Date: 2018-09-19 16:24:16.197453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f5f4b3b169'
down_revision = 'a6ea9f14acd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('message', sa.String(), nullable=True))
    op.drop_column('messages', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'message')
    op.drop_column('messages', 'email')
    # ### end Alembic commands ###
